### ISSUE TITLE
[Feature Request] Throttle curve

### ISSUE THREAD

**Issue by jngls** [KissUltra/firmware#1]
I am in the process of trying out Kiss Ultra (coming from BF) and I noticed there is no throttle curve. Throttle curve is something I've refined over the past year to a point where I'm extremely satisfied with the feel of my controls and how that relates to motion. I use a throttle curve with mid 0 (as low as it goes) and 0.5 expo.

At least in my use case, this is a fairly core part of my setup and I know I'm not the only one flying with a throttle curve. I would like to continue flying with a throttle curve (and I'd very much like that flying to be with Kiss Ultra!).

As a workaround, I can set up a curve in openTX, but to get the same simple expo curve, I'm going to have to convert an algebraic curve to a set of XY points then transfer those into my controller, which obviously isn't great from a workflow and tweakability point of view. I will also need to adjust my BF quads to match Kiss' linear throttle or select different models when flying. This workaround potentially also sacrifices precision due to the limited range of values sent to the FC.

Hence, I'd like to create this feature request for a throttle curve in the Kiss Ultra FC firmware.

**Comment by fedorcomander** [comment]
hi. kiss doesnt have it and frankly never needed by any of kiss pilots. radio setup would be a easier now. and u will not loose resolution. ;) you will have to make new model  for kiss ultra anyhow!
---
Cheers,
Alex

**Comment by jngls** [comment]
Ahh I didn't realise you are Alex Fedorov when I asked in the discord! Ok. Thanks for your reply. It's true even most BF pilots don't fly with throttle curve. But I think that's due to some misleading comments early on by some high profile content creators, saying you shouldn't fly with throttle curves.

Having flown with a throttle curve for over a year, I literally cannot go back to linear. Expo just feels too good!

But all comments aside, I will use my controller's curve feature. If you ever support throttle curves in the future, I will be happy.

**Comment by jngls** [comment]
I've made a quick spreadsheet to convert Betaflight throttle curves to OpenTX curves:
https://docs.google.com/spreadsheets/d/19sozGBeEKNTZKmwVqiF-9rQPb9yEr0ax9Rf3sd-q_H0/edit?usp=sharing

**Comment by KissUltra** [comment]
Nice! Don’t forget to share it with others on our discord.
