### ISSUE TITLE
B61 frame radio throttle values is high

### ISSUE THREAD

**Issue by qiyanlong** [KissUltra/firmware#2]
I use futaba 16iz+ tbs crossfire lite，radio pwm default value is 1094-1933 . osd  thr value show 9%.used b61 frame on osd alert radio throttle values is high. I can't arm.  writing b60 frame ，osd  thr value show 9% ，arm is ok .is a bug?

**Comment by KissUltra** [comment]
make sure your radio sends 1000-2000 as a start. use your trims/range on RADIO.

**Comment by qiyanlong** [comment]
I have four planes，one planes used kiss,three planes used bf  ,b60 frame is ok .I want a model control all planes

**Comment by qiyanlong** [comment]
change radio sends 1000-2000 unscientific

**Comment by KissUltra** [comment]
make NEW model.

**Comment by KissUltra** [comment]
What you doing is WRONG. You must have separate model for quads/planes etc. Besides you are loosing 20% of your stick range, it’s wrong on so many levels.

**Comment by KissUltra** [comment]
> change radio sends 1000-2000 unscientific

Again, make sure in data output tab u can see 1000-2000 range.

**Comment by qiyanlong** [comment]
ok I try it

**Comment by KissUltra** [comment]
let me know how it goes. and better get on discord. link is in the gui. ---Cheers,AlexOn 13 Aug 2024, at 15:37, qiyanlong ***@***.***> wrote:﻿
ok I try it

**Comment by qiyanlong** [comment]
I don't think setting the radio range is a good idea。There are 9 and more channels that need to be set on Futaba.Some channels Range cannot be set to 2000 。currently using the b60 firmware

**Comment by qiyanlong** [comment]
The throttle  in betaflight can be set to a specific value. Have you considered adding a set travel range.

**Comment by KissUltra** [comment]
please do as you suggested. ---Cheers,AlexOn 13 Aug 2024, at 16:20, qiyanlong ***@***.***> wrote:﻿
I don't think setting the radio range is a good idea。There are 9 and more channels that need to be set on Futaba.Some channels Range cannot be set to 2000 。currently using the b60 firmware

**Comment by KissUltra** [comment]
not gonna happen. u have radio. it has endpoints. you have trims. u do it on radio. radio must send 1000-2000 range. with all respect u are doing it wrong. make model. set endpoints right. and enjoy full potential. ---Cheers,AlexOn 13 Aug 2024, at 16:23, qiyanlong ***@***.***> wrote:﻿
The throttle  in betalight can be set to a specific value. Have you considered adding a set travel range.

**Comment by KissUltra** [comment]
all channels for sticks must be 1000-2000. ---Cheers,AlexOn 13 Aug 2024, at 16:32, Alex Fedorov ***@***.***> wrote:﻿not gonna happen. u have radio. it has endpoints. you have trims. u do it on radio. radio must send 1000-2000 range. with all respect u are doing it wrong. make model. set endpoints right. and enjoy full potential. ---Cheers,AlexOn 13 Aug 2024, at 16:23, qiyanlong ***@***.***> wrote:﻿
The throttle  in betalight can be set to a specific value. Have you considered adding a set travel range.

**Comment by qiyanlong** [comment]
OK I will try it.Thanks
